version: '3.8'

services:
  transcription-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: transcription-server
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config:ro
      - ./server:/app/server:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - transcription-network

  # Optional: nginx proxy for production
  nginx:
    image: nginx:alpine
    container_name: transcription-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - transcription-server
    restart: unless-stopped
    networks:
      - transcription-network
    profiles:
      - production

networks:
  transcription-network:
    driver: bridge